from pydantic import BaseModel, Field

class DestinyDefinitions(BaseModel):
    DestinyArtDyeChannelDefinition: str
    DestinyArtDyeReferenceDefinition: str
    DestinyPlaceDefinition: str
    DestinyActivityDefinition: str
    DestinyActivityTypeDefinition: str
    DestinyClassDefinition: str
    DestinyGenderDefinition: str
    DestinyInventoryBucketDefinition: str
    DestinyRaceDefinition: str
    DestinyUnlockDefinition: str
    DestinyStatGroupDefinition: str
    DestinyProgressionMappingDefinition: str
    DestinyFactionDefinition: str
    DestinyVendorGroupDefinition: str
    DestinyRewardSourceDefinition: str
    DestinyUnlockValueDefinition: str
    DestinyRewardMappingDefinition: str
    # DestinyRewardSheetDefinition: Field(exclude=True)
    DestinyItemCategoryDefinition: str
    DestinyDamageTypeDefinition: str
    DestinyActivityModeDefinition: str
    DestinyMedalTierDefinition: str
    DestinyAchievementDefinition: str
    DestinyActivityGraphDefinition: str
    DestinyActivityInteractableDefinition: str
    DestinyBondDefinition: str
    DestinyCharacterCustomizationCategoryDefinition: str
    DestinyCharacterCustomizationOptionDefinition: str
    DestinyCollectibleDefinition: str
    DestinyDestinationDefinition: str
    DestinyEntitlementOfferDefinition: str
    DestinyEquipmentSlotDefinition: str
    DestinyEventCardDefinition: str
    DestinyFireteamFinderActivityGraphDefinition: str
    DestinyFireteamFinderActivitySetDefinition: str
    DestinyFireteamFinderLabelDefinition: str
    DestinyFireteamFinderLabelGroupDefinition: str
    DestinyFireteamFinderOptionDefinition: str
    DestinyFireteamFinderOptionGroupDefinition: str
    DestinyStatDefinition: str
    DestinyInventoryItemDefinition: str
    DestinyInventoryItemLiteDefinition: str
    DestinyItemTierTypeDefinition: str
    DestinyLoadoutColorDefinition: str
    DestinyLoadoutIconDefinition: str
    DestinyLoadoutNameDefinition: str
    DestinyLocationDefinition: str
    DestinyLoreDefinition: str
    DestinyMaterialRequirementSetDefinition: str
    DestinyMetricDefinition: str
    DestinyObjectiveDefinition: str
    DestinySandboxPerkDefinition: str
    DestinyPlatformBucketMappingDefinition: str
    DestinyPlugSetDefinition: str
    DestinyPowerCapDefinition: str
    DestinyPresentationNodeDefinition: str
    DestinyProgressionDefinition: str
    DestinyProgressionLevelRequirementDefinition: str
    DestinyRecordDefinition: str
    DestinyRewardAdjusterPointerDefinition: str
    DestinyRewardAdjusterProgressionMapDefinition: str
    DestinyRewardItemListDefinition: str
    DestinySackRewardItemListDefinition: str
    DestinySandboxPatternDefinition: str
    DestinySeasonDefinition: str
    DestinySeasonPassDefinition: str
    DestinySocialCommendationDefinition: str
    DestinySocketCategoryDefinition: str
    DestinySocketTypeDefinition: str
    DestinyTraitDefinition: str
    DestinyUnlockCountMappingDefinition: str
    DestinyUnlockEventDefinition: str
    DestinyUnlockExpressionMappingDefinition: str
    DestinyVendorDefinition: str
    DestinyMilestoneDefinition: str
    DestinyActivityModifierDefinition: str
    DestinyReportReasonCategoryDefinition: str
    DestinyArtifactDefinition: str
    DestinyBreakerTypeDefinition: str
    DestinyChecklistDefinition: str
    DestinyEnergyTypeDefinition: str
    DestinySocialCommendationNodeDefinition: str
    DestinyGuardianRankDefinition: str
    DestinyGuardianRankConstantsDefinition: str
    DestinyLoadoutConstantsDefinition: str
    DestinyFireteamFinderConstantsDefinition: str
    DestinyGlobalConstantsDefinition: str

    class Config:
        extra = "allow"